services:
  frontend:
    image: stocknear-frontend:latest
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_STOCKNEAR_API_KEY=${VITE_STOCKNEAR_API_KEY}
      - HOST=${HOST}
      - PORT=${PORT}
    entrypoint: [ "npm", "run", "dev" ]